language: cpp

compiler:
  - gcc
  
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install doxygen

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build . --target package
  - cd ..
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master