language: cpp

compiler:
  - gcc
  
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install doxygen

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cmake --build . --target package
  - cd ..
  - doxygen Doxyfile

deploy1:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
	
deploy2:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uevgeny9042:$BINTRAY_API_KEY "https://api.bintray.com/content/rtti/homework/homework04/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"	